config/routes.rb
COSC617Healthylife::Application.routes.draw do
 
  resources :progresses
 

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  match '/oauth2/token' => 'goals#preset'

end

app/models/ability.rb
class Ability
  include SocialStream::Ability

  def initialize(subject)
    super
  can :manage, :all
    # Add your authorization rules here
    # For instance:
    #    can :create, Comment
    #    can [:create, :destroy], Post do |p|
    #      p.actor_id == Actor.normalize_id(subject)
    #    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  include SocialStream::Models::Object
  attr_accessible :article_type, :body, :subject,:activity_object_id,:author_id, :user_author_id, :owner_id,:user_id
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include SocialStream::Models::Object
  attr_accessible :date, :description, :name, :priority, :status, :activity_object_id,:author_id, :user_author_id, :owner_id
  has_many :progresses
end

app/models/progress.rb
class Progress < ActiveRecord::Base
  attr_accessible :created, :description, :number, :goal_id
  belongs_to :goal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SocialStream::Controllers::Objects
   def index
    @articles = Article.find_all_by_user_id(current_user.id)
     
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end
   

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def article_params
      params.require(:article).permit(:article_type, :body, :subject,:user_id)
    end
    def allowed_params
    [:article_type, :body, :subject,:user_id]
  end
   
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  include SocialStream::Controllers::Objects
  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end
  
   # GET /goals/preset
  # GET /goals/preset.json
  def preset
 
    @goal = Goal.new

    respond_to do |format|
      format.html # preset.html.erb
      format.json { render json: @goal }
    end
  end
end

# GET /goals/1
# GET /goals/1.json
def progress
    @goal = Goal.find(params[:id])

    respond_to do |format|
      format.html # progress.html.erb
      format.json { render json: @goal }
    end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def permitted_params
      params.require(:goal).permit(:date, :description, :name, :priority, :status)
    end
    
    def allowed_params
      [:date, :description, :name, :priority, :status]
    end
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  # GET /progresses
  # GET /progresses.json
  def index
    @progresses = Progress.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @progresses }
    end
  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
    @progress = Progress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @progress }
    end
  end

  # GET /progresses/new
  # GET /progresses/new.json
  def new
    @progress = Progress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @progress }
    end
  end

  # GET /progresses/1/edit
  def edit
    @progress = Progress.find(params[:id])
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: 'Progress was successfully created.' }
        format.json { render json: @progress, status: :created, location: @progress }
      else
        format.html { render action: "new" }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    @progress = Progress.find(params[:id])

    respond_to do |format|
      if @progress.update_attributes(progress_params)
        format.html { redirect_to @progress, notice: 'Progress was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @progress = Progress.find(params[:id])
    @progress.destroy

    respond_to do |format|
      format.html { redirect_to progresses_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def progress_params
      params.require(:progress).permit(:created, :description, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/articles/_form.html.erb
<section id="new_article">
<%= render partial: 'toolbar/home' %>
 
<div id="article_form" >
<%= form_for(@article) do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :article_type %><br />
    <%= f.text_field :article_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %></div>
 
</section>

app/views/articles/_timeline.html.erb
 
<%= div_for article do %>
    
  <div class="subject">
    <% if article.subject %>
      <h6>
        <%= article.subject %>
      </h6>
    <% end %>
    <div class="body">
      <%= article.body %>
    </div>
     
    <%= render partial: 'objects/timeline_description',
               object: article,
               as: :obj %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render partial: 'toolbar/home' %>
 
<% if @articles.any? %> 
 <%= render partial: 'sidebar/show' %>
 <div id="article_feed">
 <h1>My Article Feed </h1>
<% @articles.each do |article| %>
  <tr>
    <td>
    	<%= link_to image_tag(current_user.logo.url('small'),
        :alt => current_user.name), current_user %>
      </td>
     
 
 	 
 	<td><%= article.subject %><br></td>
 	<tr><td>           <td>
    <td><%= link_to 'See Details...  ', article %></td>
    <td><%= link_to 'Update    ', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr></tr>  <br>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>
<% else %>
<h1> Sorry, you don't have any article </h1>
<h1><%= link_to 'Create Article', new_article_path %></h1>
<%end%>
 
 

app/views/articles/new.html.erb
<%= render 'form' %>

 

app/views/articles/show.html.erb
 
<%= div_for @article do %>
<div class="avatar pull-left">
    <div class="media-object">
      <%= link_to image_tag(current_user.logo.url('original'),
        :alt => current_user.name), current_user %>
    </div>
  </div>
  <header class="media-heading">
    <%= current_user.name %>
<div class="subject">
    <% if @article.subject %>
      <h6>
        <%= @article.subject %>
      </h6> 
      
    <% end %>
    <div class="article_type">
      <%= @article.article_type %>
    </div>  
    <div class="body">
      <%= @article.body %>
 <% end %>
 
 <p >Comments: </p>
 </div>
    <div class="comment" >
    <%=  render  :partial  =>  'activities/comments',  :locals  =>  {  :activity  => @article.post_activity  }  %>
    </div>

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/_timeline.html.erb
 
<%= div_for goal do %>
    
  <div class="subject">
    <% if goal.name %>
      <h6>
        <%= goal.name %>
      </h6>
    <% end %>
    <div class="body">
      <%= goal.description %>
    </div>
     
    <%= render partial: 'objects/timeline_description',
               object: goal,
               as: :obj %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<table>
	<% @goals.each do |goal|%>
	<tr>
		<td class = "list_description">
			<dl>
				<dt><%= goal.name%></dt>
				<dd><%= goal.description%></dd>
				<p><ss>Deadline: </ss><%= goal.date%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<ss>Status: </ss><%= goal.status%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<ss>Priority: </ss><%= goal.priority%></p>
			</dl>
		</td>
		<td class = "list_actions">
			<%= link_to 'Show', goal %><br/>
			<%= link_to 'Edit Goal', edit_goal_path(goal) %><br/>
			<%= link_to 'Add Progress', :controller => 'progresses', :action => 'new'%><br/>
			<%= link_to 'View All Progress', :controller => 'progresses', :action => 'index'%><br/>
			<%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %>
		</td>
	</tr>
	<%end%>
</table>
<%= link_to 'New Goal', new_goal_path %><br/>
<%= link_to 'New Preset Goal', :controller => 'goals', :action => 'preset'%>

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/preset.html.erb
<h1>Preset Goals</h1>

<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
     <%= f.select :name, [['Couch to 5K', 'Couch to 5K'], ['Run a Mile'],["Start a healthy Nutrition Plan"], ["Improve Flexibility and Balance"], ["Improve Immune System"], 
     ["Log Food Daily"], ["Drink at least 64 ounces of water a day"]]%>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', goals_path %>

app/views/goals/progress.html.erb
<h1>Progress</h1>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @goal.name %>
</p>

<p>
  <b>Description:</b>
  <%= @goal.description %>
</p>

<p>
  <b>Date:</b>
  <%= @goal.date %>
</p>

<p>
  <b>Status:</b>
  <%= @goal.status %>
</p>

<p>
  <b>Priority:</b>
  <%= @goal.priority %>
</p>


<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/progresses/_form.html.erb
<%= form_for(@progress) do |f| %>
  <% if @progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@progress.errors.count, "error") %> prohibited this progress from being saved:</h2>

      <ul>
      <% @progress.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :created %><br />
    <%= f.date_select :created %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progresses/edit.html.erb
<h1>Editing progress</h1>

<%= render 'form' %>

<%= link_to 'Show', @progress %> |
<%= link_to 'Back', progresses_path %>

app/views/progresses/index.html.erb
<h1>Goal Progress</h1>
<table>
	<% @progresses.each do |progress| %>
	<tr>
		<td class = "list_description">
			<dl>
				<dt>Number: <%= progress.number%></dt>
				<dd>Description: <%= progress.description%></dd>
				<p><ss>Submitted on: </ss><%= progress.created %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</dl>
		</td>
		<td class = "list_actions">
			<%= link_to 'Show', progress %><br/>
			<%= link_to 'Edit Progress', edit_progress_path(progress) %><br/>
			<%= link_to 'Destroy', progress, method: :delete, data: { confirm: 'Are you sure?' } %><br/>
		</td>
	</tr>
	<%end%>
</table>

<br />

<%= link_to 'New Progress', new_progress_path %></br/>
<%= link_to 'Back to Goals', goals_path %>

app/views/progresses/new.html.erb
<h1>New progress</h1>

<%= render 'form' %>

<%= link_to 'Back', progresses_path %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @progress.number %>
</p>

<p>
  <b>Description:</b>
  <%= @progress.description %>
</p>

<p>
  <b>Created:</b>
  <%= @progress.created %>
</p>


<%= link_to 'Edit', edit_progress_path(@progress) %> |
<%= link_to 'Back', progresses_path %>